post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # 1. هذا التعديل الأهم: استبعاد معمارية arm64 للمحاكي لمنع تعارض المكتبات
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # 2. ضمان توحيد إصدار النظام لجميع المكتبات
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      
      # 3. إعدادات إضافية لضمان استقرار البناء
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end